// vim: set syntax=asciidoc:

// set asciidoc attributes
:toc:       1
:numbered:  1
:data-uri:  1
:icons:     1
:sectids:   1
:iconsdir: /usr/local/etc/asciidoc/images/icons

// create blank lines, from: http://bit.ly/1PeszRa
:blank: pass:[ +]

:sectlinks: 1
//:sectanchors: 1

# One User's Convert-to-Tag-Based-Email Challenges
author github.com@johnnyutahh.com
0.x, May 2015:
Last updated {docdate} {doctime}

toc::[]

<<<
:numbered:

<<<

## The Problem

. I'm seeking a better paradigm over my IMAP-folder-only email management
. existing (2015-05-17) environment
** Primary http://en.wikipedia.org/wiki/Email_client[MUA] =
   Mozilla Thunderbird 17.0.11
** OS = Mac OS 10.9.5
** no tagging
** \~4300 IMAP-based email folders with \~1MM mail msgs
   from multiple servers/accounts
*** doesn't include pruned/archived emails, whose indexing/searching
    also desired

See <<problem_details>> and
http://bit.ly/email-tag-based-user-paradigm[investigation notes]
for more context.
    
## The Possible Solutions

I'm currently, as of 2015-05-16, seeking:

1. fast search on my entire maildir collection (my "email database"),
2. leverage tag-based categorization, and
3. integrate with external-to-MUA text-process tools.

This probably means a tag-based-message-classification,
fast-index-search toolset that integrates with a
lower-level/text-primitive MUA (read mutt vs TB). The only
reasonably-available, competitive mechanisms that I've yet found to
provide this (core) functionality appear to be:

1. http://notmuch.org[notmuch]
2. http://www.djcbsoftware.nl/code/mu[mu (maildir-utils)]

## Choosing

1. Initial tests show
   https://gist.github.com/johnnyutahh/f4e3d2d3fb07de5fa146[notmuch
   performing 10-15 times faster than mu].
   ** Question: were this tests configured and executed correctly? The
      performance difference is remarkable, and concerns about correct
      application setup, environment.

2. mu can embed its metadata (tags, etc) "natively" into
   the IMAP content/messages. notmuch can not. However,
   http://www.muchsync.org/[muchsync] (maybe other tools?) can replicate
   this metadata, but it takes additional process+infrastructure.

3. #1 greatly outweighs #2. As of now, notmuch "wins."

More details at my https://github.com/johnnyutahh/tag-based-email/blob/master/email-tag-based-user-paradigm.txt[investigation notes].

## Implementation

Since notmuch wins, I make a notmuch-specific implementation.

Tools:

1. email-to-maildir gathering: http://isync.sourceforge.net/[mbsync] [solved]

** I'm not (yet, at least) looking to debate this choice here.
   For now, I seem to have mbsync working nicely. Search
   http://bit.ly/1EdmDkW["mbsync vs offlineimap"] to read more.

2. http://notmuch.org[notmuch] initial setup [solved]

3. MUA setup [in progress]

** currently both
http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz] and
https://github.com/pazz/alot[alot] are being configured, investigated

4. Message-tagging tool(s). [not yet started]
** http://afew.readthedocs.org/en/latest[afew] currently looks best.

5. Replicating+synchronizing notmuch metadata across machines. [not yet started]
** http://www.muchsync.org[muchsync] currently looks best.

## User-adoption Challenges

My adjustment of my workflow/paradigm appears to be the primary
challenge for my adoption of this tag-based system. This includes but
may not be limited to:

1. https://lists.fedoraproject.org/pipermail/mutt-kz/2012-April/000043.html[Moving msgs after applying tags].

   I'm used to moving messages between folders in order to classify.
   Further, I will like to keep a clean Inbox and other folders, for my
   non-notmuch-based email clients, thus requiring message moving.

   I'd like to ensure that once I associated notmuch-metadata (by adding
   tags, or whatever metadata/etc scenarios might be involved with
   notmuch) with a message, that said metadata "stays" with a message,
   regardless of wherever I put said message. Is this the way it works
   "out of the box"?

2. next

   blah 
    

[id='problem_details']
## Appendix: Problem Details

(DISCLAIMER: This sections is under construction, and not complete.)

OS X is great, but TB is difficult. Thunderbird is old, buggy,
troublesome, slow, basically inextensible (for me, anyway), and as
I understand it, feature frozen. I'm tired of debating with the
Mozillazine support team about TB's bugs and limitations. Among other
things, it's IMAP sync is slow and unreliable. It literally (and
unfortunately, inconsistently) deletes IMAP folders on it's own whim,
asynchronously, sometimes when I least expect it. Sometimes it loses
track of the folders it didn't delete, and simply creates new ones,
bloating my mbox (TB only reliably support mbox) files terribly over
time. Or simply spot-use TB or Outlook where I have to send formatted
email.

Additionally, the TB text/formatting editor is legendarily bad/buggy.
I'd desperately prefer to simply edit in vim, and edit rich/html text in
markdown or asciidoc and convert to html with a rendering engine, and I
suspect I could script-integrate such capability... if I had an MUA that
could play nicely with external scripts.

Further, I'm a keyboard jockey--eg: vim lover--and Python programmer.
I've maxed out TB's keyboard-shortcut-ness best I can tell, and it's
still limiting. I have external tools (some developed by me and/or my
team) to parse and perform "magic" (like task-tracking and bug-report
integration) on email folders and individual messages, and TB--with it's
lack of proper maildir support and difficult extensibility--makes it if
not close-to-impossible to integrate with the external tools.

In short, it's time to move on from Thunderbird.

{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
