// vim: set syntax=asciidoc:

// set asciidoc attributes
:toc:       1
:numbered:  1
:data-uri:  1
:icons:     1
:sectids:   1
:iconsdir: /usr/local/etc/asciidoc/images/icons

// create blank lines, from: http://bit.ly/1PeszRa
:blank: pass:[ +]

:sectlinks: 1
//:sectanchors: 1

# One User's Convert-to-Tag-Based-Email Challenges
author github.com@johnnyutahh.com
0.x, May 2015:
Last updated {docdate} {doctime}

toc::[]

<<<
:numbered:

<<<

## Purpose

### Summary

https://github.com/johnnyutahh[I] am new to what I call "tag-based
email" systems, and I'm investigating the transition from a "large
IMAP folder collection" to a tag-based system. I wrote this initial
document draft because:

. Near-term: it hopefully provides the best chance for an efficient
  sand uccessful transition - if the tag-based community can provide
  significant and timely feedback.

. Longer-term: the tag-based email community might reuse this content
  (which will hopefully mature as the problems are solved) to better
  help others like me in the future. I couldn't find a resource like
  this elsewhere, so maybe this content might be useful as a basis to
  help fill some gaps. To this end, I strongly encourage forks + pull
  requests of this content.

TODO:
+ summarize my user profile/background here?

### Details

However, the tag-based-classification paradigm seems _significantly_
different, and may (or may not?) take some time to master, or at least
assimilate. See <<user_adoption_challenges>>. Specifically, opening
https://github.com/pazz/alot[alot] for the first time and looking at a
staggering 50k+ emails in my "inbox" can give someone pause; hopefully
<<initial_tagging>> will take care of that.

Further, the tag-based (as I call it) resources to document new-user
(like me) paradigm shifts and list available toolsets seem to be
scattered. Hence this document, as a "draft" precursor.

Most-important considerations/questions form the "tag-based" email
community: what if anything am I missing? For any of my descriptions
below, is there a better way/tool/approach/workflow?

I'd prefer not to spin my wheels trying to solve problems with my
custom/unique workflow/solutions that may have been automatically solved
elsewhere by tools I can reuse.

## The Problem

. I'm seeking a better paradigm over my current, IMAP-folder-only,
  high-capacity email management.

** Among other things, moving _and_ copying emails to a variety of IMAP
   folders, depending on the "classification" needs, gets cumbersome.

** Searching my entire email-message collection with an MUA like
   Thunderbird (see below) takes impossibly too long.

. existing (2015-05-17) environment
** Primary http://en.wikipedia.org/wiki/Email_client[MUA] =
   Mozilla Thunderbird 17.0.11
** OS = Mac OS 10.9.5
** no "tagging"
** approx 4300 IMAP-based email folders with approx 1 million mail msgs
   from multiple servers/accounts
*** doesn't include pruned/archived emails, whose indexing/searching
    also desired

See <<problem_details>> for more context.
    
## The Solution Options

After a reasonable search of what tools are currently available, I'm
currently seeking:

1. fast search on my entire maildir collection (my "email database"),
2. leverage tag-based categorization, and
3. integrate with external-to-MUA text-process tools.

(It's fair to ask: did I come up with these requirements by
"adjusting" to what tools are currently available, or by independently
dreaming up my own specifications? More the former. I'd much prefer
http://bit.ly/JARVIS-wikia[Jarvis] be my email interface, but he's not
currently or at least economically available.)

The only mechanisms that I've yet found to provide this (core)
functionality appear to be:

1. http://notmuch.org[notmuch]
2. http://www.djcbsoftware.nl/code/mu[mu (maildir-utils)]

## Choosing

1. Initial tests show
   https://gist.github.com/johnnyutahh/f4e3d2d3fb07de5fa146[notmuch
   performing approx 15 times faster than mu].

   ** Question: where these tests configured and executed correctly? The
      performance difference is remarkable, generating concerns about
      correct application setup, environment.

2. mu can embed its metadata (tags, etc) "natively" into
   the IMAP content/messages. notmuch can not. However,
   http://www.muchsync.org/[muchsync] (maybe other tools?) can replicate
   this metadata, but it takes additional process+infrastructure.

3. #1 greatly outweighs #2. Because of this, notmuch "wins," while I
   await feedback from the community(ies).

## Implementation

Since notmuch <<Choosing,won>>, the following outlines but may not be
limited to a notmuch-specific implementation/tools/etc.

### email-to-maildir gathering, fetching: mbsync [solved]

Options

* http://isync.sourceforge.net/[mbsync, aka isync]
* http://pyropus.ca/software/getmail[getmail]
* http://offlineimap.org[offlineimap]

Comments

* I'm not (yet, at least) looking to debate this choice here.
  For now, mbsync appears to working nicely for me. Search
  http://bit.ly/1EdmDkW["mbsync vs offlineimap"] to see more.

* I understand getmail the least. It's less referenced (on
  the web) for this usage/context than either offlineimap
  or mbsync. Why is this? Is it not a viable alternative to
  the above? http://pyropus.ca/software/getmail[getmail's
  website] seems to primarily (?) pitch it as a
  http://sourceforge.net/projects/fetchmail/[fetchmail] replacement.

### notmuch initial installation and setup [solved]

* http://notmuch.org[notmuch]

### notmuch initial + automated tagging

* https://readthedocs.org/projects/afew[afew] best?
* http://www.procmail.org/[procmail]?
* See <<initial_tagging>> and <<auto_tagging>> for more.

### Auto-check if mbsync replay is needed [implementation not yet started]
*  mbsync-watcher
**   https://github.com/tim-smart/node-mbsync-watcher
**   https://www.npmjs.com/package/mbsync-watcher
**   my take: it's good for client->server updates, and not vice versa
*  https://github.com/athoune/imapidle
*  mswatch
**   http://mswatch.sourceforge.net
**   requires IMAP-server-side shell access - difficult
**   wrapping `imapidle` with a `mbsync` trigger seems like good alternative

### MUA setup [in progress]

* currently both
http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz] and
https://github.com/pazz/alot[alot] are being configured, investigated

### Message-tagging tool(s) [implementation not yet started]
* http://afew.readthedocs.org/en/latest[afew] currently looks best.

### Replicating+synchronizing notmuch metadata across machines [implementation not yet started]

* http://www.muchsync.org[muchsync] currently looks best.

** muchsync apparently syncs metadata _and_ data (which may be
   unavoidable), but claims to do it as efficiently as possible.

[id='user_adoption_challenges']
## User-adoption Challenges

My adjustment of my workflow/paradigm appears to be the primary
challenge for my adoption of this tag-based system. This includes but
may not be limited to (listed in priority-first order):

### Which MUA(s)?
* http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz]
** seems to be the most-popular MUA in this space
** http://notmuchmail.org/mutttips
** https://raw.githubusercontent.com/karelzak/mutt-kz/master/README.notmuch
* https://github.com/pazz/alot[alot]
** TODO: describe the 1) promise and 2) challenges I experience with alot

### Support old-style IMAP-folder paradigm
** TODO

[id='initial_tagging']
### Initial tagging
* http://notmuchmail.org/initial_tagging
* "tagging" my large set of IMAP folders
* in particular: `Inbox` and `Spam` folders -> tags
* Is https://readthedocs.org/projects/afew[afew] best for this?

### Moving msgs after applying tags

* Context, details:
  http://bit.ly/1GimL8Q[mutt-kz thread: "Moving msgs after applying tags?"].

* Will messages retain notmuch-associated metadata (tags, etc) for
  lifetime of any message, including post-folder moves - without any
  special configuration?

** I'm used to moving messages between folders in order to classify.
    Further, I will like to keep a clean Inbox and other folders, for my
    non-notmuch-based email clients, thus requiring message moving.

** Once I associate notmuch-metadata (by adding tags, or whatever
    metadata/etc scenarios might be involved with notmuch) with a
    message, that said metadata "stays" with a message, regardless of
    wherever I put said message. Is this the way it works "out of the
    box"?

### Piping email-message content through shell commands

eg:
* http://www.davep.org/mutt/muttrc/macros.html
* http://wcm1.web.rice.edu/mutt-tips.html
* http://rhonda.deb.at/config/mutt/keys

### Configure keyboard shortcuts to any command

eg:
* http://rhonda.deb.at/config/mutt/keys
* http://dev.mutt.org/trac/wiki/MuttGuide/Macros
* http://www.mutt.org/doc/manual/manual-2.html

[id='IMAP_folders_as_tags',reftext='IMAP folders as tags']
### IMAP folders as tags
* http://notmuchmail.org/pipermail/notmuch/2010/003249.html
** http://notmuchmail.org/pipermail/notmuch/2010/003250.html

### notmuch/MUA/mutt-kz/alot folder-based searching
* not yet certain how different this is from <<IMAP_folders_as_tags>>.
* http://notmuchmail.org/pipermail/notmuch/2011/thread.html#3707
* http://bit.ly/notmuch-folder-based-searching-nabble-2011

### Address-Book/Contacts Integration

* http://notmuchmail.org/vimtips/#index1h2[notmuch: Addressbook management
  and vim]
* http://stevelosh.com/blog/2012/10/the-homely-mutt/#contacts[mutt + contacts]

### Sync notmuch tags with maildir flags
* https://github.com/spaetz/notmuchsync

### Managing message attachments
* <<forwarding_msgs_w_attachments>>
* opening attachments from MUA

[id='auto_tagging']
### Automatically tagging new messages (post initial tagging)
* http://afew.readthedocs.org/en/latest[afew]?
* employe procmail to set tags?
** http://notmuchmail.org/pipermail/notmuch/2012/thread.html#11055

[id='forwarding_msgs_w_attachments']
### Forwarding messages with attachments

* alot appears to https://github.com/pazz/alot/issues/761[have issues
  with this]

* I'm wondering if mutt-kz or others do as well

### Writing HTML-formatted messages

* Haven't yet seen this solved.
* http://bit.ly/1dfWYmr[This discussion] might be useful.

### Syncing notmuch metadata across machines
* http://notmuchmail.org/pipermail/notmuch/2010/003249.html
** http://notmuchmail.org/pipermail/notmuch/2010/003250.html
* http://www.reddit.com/r/linux/comments/2kcznk/notmuch_syncing_tags
** https://github.com/altercation/es-bin/blob/master/maildir-notmuch-sync
** https://lists.fedoraproject.org/pipermail/mutt-kz/2013-March/000136.html
* http://www.muchsync.org

### Offline Editing - Postponing Drafts

* http://stevelosh.com/blog/2012/10/the-homely-mutt/#postponing-drafts[
  The Homely Mutt: Postponing Drafts]

[id='problem_details']
## Appendix 1: Problem Details

(DISCLAIMER: This sections is under construction, and not complete.)

OS X is great, but TB is difficult. Thunderbird is old, buggy,
troublesome, slow, basically inextensible (for me, anyway), and as
I understand it, feature frozen. I'm tired of debating with the
mozillaZine support team about TB's bugs and limitations. Among other
things, it's IMAP sync is slow and unreliable. It literally (and
unfortunately, inconsistently) deletes IMAP folders on it's own whim,
asynchronously, sometimes when I least expect it. Sometimes it loses
track of the folders it didn't delete, and simply creates new ones,
bloating my mbox (TB only reliably support mbox) files terribly over
time. Or simply spot-use TB or Outlook where I have to send formatted
email.

Additionally, the TB text/formatting editor is legendarily bad/buggy.
I'd desperately prefer to simply edit in vim, and edit rich/html text in
markdown or asciidoc and convert to html with a rendering engine, and I
suspect I could script-integrate such capability... if I had an MUA that
could play nicely with external scripts.

Further, I'm a keyboard jockey--eg: vim lover--and Python programmer.
I've maxed out TB's keyboard-shortcut-ness best I can tell, and it's
still limiting. I have external tools (some developed by me and/or my
team) to parse and perform "magic" (like task-tracking and bug-report
integration) on email folders and individual messages, and TB--with it's
lack of proper maildir support and difficult extensibility--makes it if
not close-to-impossible to integrate with the external tools.

In short, it's time to move on from Thunderbird.

## Appendix 2: General Setup Guides

(Previously-referenced guides or sections of guides listed below are not
duplicated here.)

* http://dbp.io/essays/2013-06-21-hackers-replacement-for-gmail.html
* mutt + notmuch
  (non- http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz] style)
** http://stevelosh.com/blog/2012/10/the-homely-mutt/
*** may get replaced by mutt-kz, but other things possibly still useful:
**** http://stevelosh.com/blog/2012/10/the-homely-mutt/#full-text-searching
* mutt in general
** http://wcm1.web.rice.edu/mutt-tips.html
** http://www.guckes.net/Mutt/setup.html
** http://objectmix.com/mutt/202060-whaaah-cant-see-svens-setup-page.html
* http://bit.ly/notmuch--how-i-learned-to-stop-worrying-and-love-the-mail

{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}

