// vim: set syntax=asciidoc:

// set asciidoc attributes
:toc:       1
:numbered:  1
:data-uri:  1
:icons:     1
:sectids:   1
:iconsdir: /usr/local/etc/asciidoc/images/icons

// create blank lines, from: http://bit.ly/1PeszRa
:blank: pass:[ +]

:sectlinks: 1
//:sectanchors: 1

# One User's Convert-to-Tag-Based-Email Challenges
author github.com@johnnyutahh.com
0.x, May 2015:
Last updated {docdate} {doctime}

toc::[]

<<<
:numbered:

<<<

## Purpose

### Summary

https://github.com/johnnyutahh[I] am new to what I call "tag-based
email" systems, and I'm investigating the transition from a "large
IMAP folder collection" to a tag-based system. I wrote this initial
document draft because:

. Near-term: it hopefully provides the best chance for an efficient
  and successful transition -- if the tag-based community can provide
  significant and timely feedback.

** Community members need not wait to reply to -all- issues presented;
   small responses on invidual points welcome, even preferred.

** Most important questions: what if anything am I missing? For any of
   my descriptions below, is there a better way/tool/approach/workflow?

. Longer-term: the tag-based email community might reuse this
  content--which will hopefully mature as the problems are solved--to
  better help others like me in the future.

** I couldn't find a resource like this elsewhere, so maybe this content
   might be useful as a basis to help fill some gaps. To this end, I
   strongly encourage forks + pull requests of this content. (Of course,
   please advise asap if other, similar docs exist.)

As email is my most-frequent, computer-related activity, I'd
like to "get it right." Hence the effort spent on this document.
I'm hopeful with the right system, I can make email management a
much-less-time-consuming burden.

_(DISCLAIMER: this document may be in flux as I learn and attempt to
master this domain.)_

### Details

See <<purpose_more_details>>.

[id='the_problem']
## The Problem

. I'm seeking a better paradigm over my current, IMAP-folder-only,
  high-capacity email management.

** Among other things, moving _and_ copying emails to a variety of IMAP
   folders, depending on the "classification" needs, gets cumbersome.

** Searching my entire email-message collection with an MUA like
   Thunderbird (see below) takes impossibly too long.

. existing (2015-05-17) environment
** Primary http://en.wikipedia.org/wiki/Email_client[MUA] =
   Mozilla Thunderbird 17.0.11
** OS = Mac OS 10.9.5
** no "tagging"
** approx 4300 IMAP-based email folders with approx 1 million mail msgs
   from multiple servers/accounts
*** doesn't include pruned/archived emails, whose indexing/searching
    also desired

See <<problem_details>> for more context.
    
## The Solution Options

After reviewing currently-available tools, I'm seeking:

1. fast search on my entire email-message collection (my "email database"),
2. to leverage tag-based email categorization, and
3. integrate with external-to-MUA text-processing tools - namely ones
   me and my team have developed.

(It's fair to ask: did I come up with these requirements by
"adjusting" to what tools are currently available, or by independently
dreaming up my own specifications? More the former. I'd much prefer
http://bit.ly/JARVIS-wikia[Jarvis] be my email interface, but he's not
currently or at least economically available.)

My choice seems to hinge on these 2 applications:

1. http://notmuch.org[notmuch]
2. http://www.djcbsoftware.nl/code/mu[mu (maildir-utils)]

Most of my (new) email-system setup seems to depend on the above choice.
What other tools/options might I be overlooking?

## Choosing

Tradeoffs:

1. Initial tests show
   https://gist.github.com/johnnyutahh/f4e3d2d3fb07de5fa146[notmuch
   performing approx 15 times faster than mu].

   ** Question: where these tests configured and executed correctly? The
      performance difference is remarkable, generating concerns about
      correct application setup, environment.

2. mu can embed its metadata (tags, etc) "natively" into
   the IMAP content/messages. notmuch can not. However,
   http://www.muchsync.org/[muchsync] (maybe other tools?) can replicate
   this metadata, but it takes additional process+infrastructure.

3. #1 greatly outweighs #2. Because of this, notmuch "wins," while I
   await feedback from the community(ies).

What other tradeoffs might motivate me to employ
http://www.djcbsoftware.nl/code/mu[mu] over http://notmuch.org[notmuch]?

## Implementation

Since notmuch <<Choosing,won>>, the following outlines but may not be
limited to a notmuch-specific implementation/tools/etc.

### email-to-maildir gathering, fetching

Currently solved with http://isync.sourceforge.net/[mbsync, aka isync].

Options

* http://isync.sourceforge.net/[mbsync, aka isync]
* http://offlineimap.org[offlineimap]
* http://pyropus.ca/software/getmail[getmail]

Comments

* I'm not (yet, at least) looking to debate this choice here.
  For now, mbsync appears to working nicely for me. Search
  http://bit.ly/1EdmDkW["mbsync vs offlineimap"] to see more.

* I understand getmail the least. It's less referenced (on
  the web) for this usage/context than either offlineimap
  or mbsync. Why is this? Is it not a viable alternative to
  the above? http://pyropus.ca/software/getmail[getmail's
  website] seems to primarily (?) pitch it as a
  http://sourceforge.net/projects/fetchmail/[fetchmail] replacement.

### notmuch initial installation and setup

* Currently solved: http://notmuch.org[notmuch]

### notmuch initial + automated tagging

* https://readthedocs.org/projects/afew[afew] best?
* http://www.procmail.org/[procmail]?
* See <<initial_tagging>> and <<auto_tagging>> for more.

### Auto-check if mbsync replay is needed

(This implementation has not yet started.)

#### client->server checking

* mbsync-watcher
** https://github.com/tim-smart/node-mbsync-watcher
** https://www.npmjs.com/package/mbsync-watcher
** my take: it's good for client->server updates, and not vice versa
** Problem: I do _not_ want it to sync _all_ my 4k+ folders every 5
   minutes, as that's too much overhead. Hopefully there's a way to disable
   this.

#### server->client checking

*  https://github.com/athoune/imapidle
*  mswatch
**   http://mswatch.sourceforge.net
**   requires IMAP-server-side shell access - difficult
**   wrapping `imapidle` with a `mbsync` trigger seems like good alternative
**   this might also be a client->server option

### MUA setup

(Implementation currently in progress.)

* Currently both http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz]
  and https://github.com/pazz/alot[alot] are being configured,
  investigated. See <<which_MUAs>>.

### Message-tagging

(This implementation has not yet started.)

* http://afew.readthedocs.org/en/latest[afew] currently looks best.

### Replicating+synchronizing notmuch metadata across machines

(Implementation currently in progress.)

* http://www.muchsync.org[muchsync] currently looks best.

** muchsync apparently syncs metadata _and_ data (which may be
   unavoidable), but claims to do it as efficiently as possible.

[id='user_adoption_challenges']
## User-adoption Challenges

My adjustment of my workflow/paradigm appears to be the primary
challenge for my adoption of this tag-based system. This includes but
may not be limited to (listed in priority-first order):

[id='which_MUAs']
### Which MUA(s)?

* http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz]
** seems to be the most-popular MUA in this space
** http://notmuchmail.org/mutttips
** https://raw.githubusercontent.com/karelzak/mutt-kz/master/README.notmuch

* vim front-end for notmuch
** http://git.notmuchmail.org/git/notmuch/blob/HEAD:/vim/README
** http://notmuchmail.org/vimtips/

** <<my_user_profile,I'm a heavy vim user>>, and while this approached
   seemed initially appealing, the depth seems so small, that I haven't
   even bothered to try this. Am I overlooking a useful (in comparison
   to the others) tool?

* https://github.com/pazz/alot[alot]

** https://github.com/pazz/alot[alot] looks tremendously promising,
   possibly my best long-term solution, especially given
   <<my_user_profile,my user profile>> (namely I'm a vim user and a
   Python programmer--seems to mirror well). However, the available
   documentation/resources are far more sparse. The user-manual content
   is almost impeccable, and pazz seems to do a great job to stay on top
   of all issues. But it's hard to find practical resources like example
   config files, procedural setup, blog/setup guides, etc. Maybe in part
   because it's not as widely used.

*** Speculating: a smaller effort to provide setup + config-file
    examples might go a long way to solve this problem.

* There's other http://notmuchmail.org/frontends[frontends]...

** ...but none seem as appealing to <<my_user_profile,me>> as the
   above. Am I overlooking any solutions that might fit well with my
   <<my_user_profile,user profile>>?

### Support old-style IMAP-folder paradigm

* While I may be be moving to a a tag-based paradigm, I still
  need to access my 4k+ IMAP folders as I did before. Any primary
  MUA/interface/IMAP-client I choose needs to support IMAP-folder-based
  paradigms (copying and moving to folders, etc) that I currently employ
  with <<the_problem,Mozilla Thunderbird>>.

[id='initial_tagging']
### Initial tagging
* http://notmuchmail.org/initial_tagging
* "tagging" my large set of IMAP folders
* in particular: `Inbox` and `Spam` folders -> tags
* Is https://readthedocs.org/projects/afew[afew] best for this?

### Moving msgs after applying tags

* Context, details:
  http://bit.ly/1GimL8Q[mutt-kz thread: "Moving msgs after applying tags?"].

* Will messages retain notmuch-associated metadata (tags, etc) for
  lifetime of any message, including post-folder moves - without any
  special configuration?

** I'm used to moving messages between folders in order to classify.
    Further, I will like to keep a clean Inbox and other folders, for my
    non-notmuch-based email clients, thus requiring message moving.

** Once I associate notmuch-metadata (by adding tags, or whatever
    metadata/etc scenarios might be involved with notmuch) with a
    message, that said metadata "stays" with a message, regardless of
    wherever I put said message. Is this the way it works "out of the
    box"?

### Piping email-message content through shell commands

Example potential solutions, not yet tested:

* http://www.davep.org/mutt/muttrc/macros.html
* http://wcm1.web.rice.edu/mutt-tips.html
* http://rhonda.deb.at/config/mutt/keys

### Configure keyboard shortcuts to any command

Example potential solutions, not yet tested:

* http://rhonda.deb.at/config/mutt/keys
* http://dev.mutt.org/trac/wiki/MuttGuide/Macros
* http://www.mutt.org/doc/manual/manual-2.html

[id='IMAP_folders_as_tags',reftext='IMAP folders as tags']
### IMAP folders as tags
* http://notmuchmail.org/pipermail/notmuch/2010/003249.html
** http://notmuchmail.org/pipermail/notmuch/2010/003250.html

### notmuch/MUA/mutt-kz/alot folder-based searching
* not yet certain how different this is from <<IMAP_folders_as_tags>>.
* http://notmuchmail.org/pipermail/notmuch/2011/thread.html#3707
* http://bit.ly/notmuch-folder-based-searching-nabble-2011

### Address-Book/Contacts Integration

* http://notmuchmail.org/vimtips/#index1h2[notmuch: Addressbook management
  and vim]
* http://stevelosh.com/blog/2012/10/the-homely-mutt/#contacts[mutt + contacts]

### Sync notmuch tags with maildir flags
* https://github.com/spaetz/notmuchsync

### Managing message attachments
* <<forwarding_msgs_w_attachments>>
* opening attachments from MUA

[id='auto_tagging']
### Automatically tagging new messages (post initial tagging)
* http://afew.readthedocs.org/en/latest[afew]?
* employe procmail to set tags?
** http://notmuchmail.org/pipermail/notmuch/2012/thread.html#11055

### Syncing notmuch metadata across machines
* http://notmuchmail.org/pipermail/notmuch/2010/003249.html
** http://notmuchmail.org/pipermail/notmuch/2010/003250.html
* http://www.reddit.com/r/linux/comments/2kcznk/notmuch_syncing_tags
** https://github.com/altercation/es-bin/blob/master/maildir-notmuch-sync
** https://lists.fedoraproject.org/pipermail/mutt-kz/2013-March/000136.html
* http://www.muchsync.org

### Offline Editing - Postponing Drafts

* http://stevelosh.com/blog/2012/10/the-homely-mutt/#postponing-drafts[
  The Homely Mutt: Postponing Drafts]

### Writing HTML-formatted messages

* Haven't yet seen this solved.
* http://bit.ly/1dfWYmr[This discussion] might be useful.

[id='forwarding_msgs_w_attachments']
### Forwarding messages with attachments

* alot appears to https://github.com/pazz/alot/issues/761[have issues
  with this]

* I'm wondering if mutt-kz or others do as well

[id='purpose_more_details']
## Appendix 1: Purpose: More Details

[id='my_user_profile']

My "user profile":

* https://github.com/johnnyutahh[I'm] historically-trained as a
  software and computer-systems engineer.
* Experience with variety of programming languages and OSes including
  but not limited to: C, C\++, Java, Ada, perl, Python; Windows, Unix,
  Linux, VMS, MacOSX. My favorite "Swiss army knife" language is Python.
  If I've time, I'm open to extending/fixing Pythong programs. I'd like
  to learn Ruby and https://golang.org[Go].
* I'm now more of a "business person." In spite of this:
** vim remains my primary editor (I hate moving my hand from the
   keyboard to the mouse or trackpad),
** Mac OS X is my primary computing machine,
** and I still significantly code in Python to solve "glueware" problems.
** I also dabble in Linux and MacOSX sysadmin.
* Learning new systems/languages/applications/software is old hat...
** ...but it's now harder only because of time constraints from expanded
   business responsibilities.
* And like many people, I receive a remarkable amount of email in a
  diverse set of contexts.

* Some might describe me as an impatient, unforgiving computing
  user. I _hate_ being faster than the computer. Further, when the
  computer/software/application says it's job is done, I want it to
  be _done_. However, some environments and applications perform
  significant, asynchronous activity even after reporting they are done
  servicing a request. (<<the_problem,Thunderbird>> is notorious for
  this.) And this drives me nuts. "Computer, if you need more time to
  complete a job, don't lie to me. I can go do other things while I wait
  for you. But please do not delay me further after you already said you
  were done."
 
* In summary, I'm a vim and Python lover, a keyboard jockey, and a
  fairly-technical, impatient, demanding user. That gets lots of email.

Despite my history assimilating to new applications/environments, the
tag-based-classification paradigm still seems _significantly_ different
and a bit daunting to this "old school IMAP-folder user", and may (or
may not?) take some time to master. See <<user_adoption_challenges>>.
For example, opening https://github.com/pazz/alot[alot] for the first
time and looking at a staggering 50k+ emails in my "inbox" can give
someone pause; hopefully <<initial_tagging>> will take care of that.

Further, the tag-based documentation resources--to describe
new-user-paradigm-shifts and list available toolsets--seem scattered,
disjointed, and/or non-existent for many scenarios. Hence this document.
Obviously, I'd love to find any similar, previously-overlooked
documentation resource.

In any case, I'd prefer to minimize time spinning my wheels trying
to solve problems the "wrong way" if there's already some better
method/workflow/tool that I overlooked. Hence, I write this doc in hopes
on learning the "best of breed" solutions given my user context and
preferences, and minimize having to learn everything via brute-force
experience.

[id='problem_details']
## Appendix 2: Problem Details

(DISCLAIMER: This sections is under construction, and not complete.)

OS X is great, but TB is difficult. Thunderbird is old, buggy,
troublesome, slow, basically inextensible (for me, anyway), and as
I understand it, feature frozen. I'm tired of debating with the
mozillaZine support team about TB's bugs and limitations. Among other
things, it's IMAP sync is slow and unreliable. It literally (and
unfortunately, inconsistently) deletes IMAP folders on it's own whim,
asynchronously, sometimes when I least expect it. Sometimes it loses
track of the folders it didn't delete, and simply creates new ones,
bloating my mbox (TB only reliably support mbox) files terribly over
time. Or simply spot-use TB or Outlook where I have to send formatted
email.

Additionally, the TB text/formatting editor is legendarily bad/buggy.
I'd desperately prefer to simply edit in vim, and edit rich/html text in
markdown or asciidoc and convert to html with a rendering engine, and I
suspect I could script-integrate such capability... if I had an MUA that
could play nicely with external scripts.

Further, I'm a keyboard jockey--eg: vim lover--and Python programmer.
I've maxed out TB's keyboard-shortcut-ness best I can tell, and it's
still limiting. I have external tools (some developed by me and/or my
team) to parse and perform "magic" (like task-tracking and bug-report
integration) on email folders and individual messages, and TB--with it's
lack of proper maildir support and difficult extensibility--makes it if
not close-to-impossible to integrate with the external tools.

In short, it's time to move on from Thunderbird.

## Appendix 3: General Setup Guides

(Previously-referenced guides or sections of guides listed below are not
duplicated here. I provide them here for my general reference; maybe
others will find them useful.)

* http://dbp.io/essays/2013-06-21-hackers-replacement-for-gmail.html
* mutt + notmuch
  (non- http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz] style)
** http://stevelosh.com/blog/2012/10/the-homely-mutt/
*** may get replaced by mutt-kz, but other things possibly still useful:
**** http://stevelosh.com/blog/2012/10/the-homely-mutt/#full-text-searching
* mutt in general
** http://wcm1.web.rice.edu/mutt-tips.html
** http://www.guckes.net/Mutt/setup.html
** http://objectmix.com/mutt/202060-whaaah-cant-see-svens-setup-page.html
* http://bit.ly/notmuch--how-i-learned-to-stop-worrying-and-love-the-mail

{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}

