// vim: set syntax=asciidoc:

// set asciidoc attributes
:toc:       1
:numbered:  1
:data-uri:  1
:icons:     1
:sectids:   1
:iconsdir: /usr/local/etc/asciidoc/images/icons

// create blank lines, from: http://bit.ly/1PeszRa
:blank: pass:[ +]

:sectlinks: 1
//:sectanchors: 1

# One User's Convert-to-Tag-Based-Email Challenges
author github.com@johnnyutahh.com
0.x, May 2015:
Last updated {docdate} {doctime}

toc::[]

<<<
:numbered:

<<<

## Purpose

### Summary

<<my_user_profile,I>> am new to what I call "tag-based email" systems,
and I'm investigating the transition from a "large IMAP folder
collection" to a tag-based system (most likely <<core_choice,Notmuch- or
mu-based>>). I wrote this initial document draft because:

. Near-term: it hopefully provides the best chance for an efficient
  and successful transition -- if the tag-based community can provide
  significant and timely feedback.

** The most-important questions:
.... What if anything am I missing?
.... For any descriptions below, is there a better way/tool/approach/workflow?
.... What <<user_adoption_challenges,usage scenario/workflow
     challenges>> might I be overlooking?

** Community members need not wait to reply to -all- issues presented;
   small responses on individual points are welcome, and even preferred.

*** Please provide feedback whichever way you prefer. Email-list replies
    to point topics are great. Git forks and pull's also great - easier
    for me. I can possibly provide write access to this repo, upon request.

. Longer-term: the tag-based email community might reuse this
  content--which will hopefully mature as the problems are solved--to
  better help others like me in the future.

** I searched for a similar web resource to comprehensively introduce me
   to the (seemingly) radically-different paradigm of tag-based email
   usage, <<existing_tag_based_user_intro_docs_appear_to_be_lacking,but
   I couldn't find anything>>. Maybe this document's content might be
   useful as a basis to help fill some gaps. Please advise if other,
   similar content already exists.

With the right system, I'm hopeful I can make email
management a much-less-time-consuming burden on my work... and my life.

Why write this doc instead of just trudging through the tool
testing (like everyone else presumably did to learn this space)?
<<why_spend_the_effort_to_write_this_doc,Read on>>.

_(DISCLAIMER: this document may be in flux as I learn and attempt to
master this domain.)_

### Details

See <<purpose_more_details>>.

[id='the_problem']
## The Problem

I find email classification, recall, and translation to
work/task tracking to be much more laborious than it should be.
<<computer_please_be_faster_than_me,I expect the computer to be faster
than me>>, and tailor to my preferred workflow. Instead, I'm constantly
waiting for the computer, or forced to type inefficiently, and/or
experiencing a terrible workflow.

More specifically:

. I'm seeking a better paradigm over my current, IMAP-folder-only,
  high-capacity email management.

** Among other things, moving _and_ copying emails to a variety of IMAP
   folders, depending on the "classification" needs, gets cumbersome.

** Searching my entire email-message/IMAP collection with an MUA like
   https://www.mozilla.org/en-US/thunderbird[Thunderbird] (see below)
   takes impossibly too long, and in many cases, isn't powerful or
   granular enough to get the job done.

. My existing environment
** Primary http://en.wikipedia.org/wiki/Email_client[MUA] =
   https://www.mozilla.org/en-US/thunderbird[Mozilla Thunderbird] 17.0.11
** OS = Mac OS 10.9.5 (Mavericks)
** No "tagging."
** I've approximately 4300 IMAP-based email folders with approximately 1
   million mail messages served via multiple IMAP accounts/servers.
*** This does not include pruned/archived emails, to whom I'd also like
    to applying tagging/indexing/searching workflows.

See <<problem_details>> for more context.

(An aside: why did I title this effort "tag-based email"? Seemed like as
good a way as any to more-specifically described the problem and usage
context. http://notmuchmail.org[Notmuch] calls itself the 'The mail
indexer', but lots of email systems "index," although not many do it
well. Few of them classically "tag." But I'm open to alternative-naming
suggestions.)
    
## Possible Solutions

After reviewing currently-available tools, I'm seeking:

. fast search on my entire email-message/IMAP collection (my "email database"),
. to leverage tag-based email categorization, and
. provide easy extensibility with Linux and MacOSX command-line
  "primitives" or other, custom scripts/commands.

It's fair to ask: did I come up with the above "requirements" by
a) adjusting to features from currently-available tools, or b) by
independently dreaming up my own specifications? More the former/(a).
I'd much prefer http://bit.ly/JARVIS-wikia[Jarvis] be my email
interface, but he's not currently (or at least not economically)
available.

[id='core_choice']
## Core Tool Choice

My investigation thus far suggests the implementation path hinges
on choosing 1 of the following 2 applications, as they seem to
mutually-exclusively represent the best (or at least most-popular) of
the core of email-message indexing and tagging tool suites:

1. http://notmuchmail.org[Notmuch]
2. http://www.djcbsoftware.nl/code/mu[mu (maildir-utils)]

Is this assessment accurate? What other tools/options might I be
overlooking?

[id='notmuch_won']
My comparison analysis:

1. Initial tests show
   https://gist.github.com/johnnyutahh/f4e3d2d3fb07de5fa146[Notmuch
   performing approx 15 times faster than mu].

   ** Question: where these tests configured and executed correctly? The
      performance difference is remarkable, generating concerns about
      correct application setup, environment.

2. mu can embed its metadata (tags, etc) "natively" into
   the IMAP content/messages. Notmuch can not. However,
   http://www.muchsync.org/[muchsync] (maybe other tools?) can replicate
   this metadata, but it takes additional process+infrastructure.
3. #1 greatly outweighs #2. Because of this, Notmuch "wins" (with me),
   pending feedback from others.

What other tradeoffs might motivate me to employ
http://www.djcbsoftware.nl/code/mu[mu] over http://notmuchmail.org[Notmuch]?

## Remaining Tool Choices

Since Notmuch <<notmuch_won,won>>, the following presents, but may not
be limited to, a http://notmuchmail.org[Notmuch]-specific implementation.

### Email-to-maildir gathering, fetching

Notmuch seems to work best (or maybe requires?)
the http://en.wikipedia.org/wiki/Maildir[Maildir]
format. The following tools (presumably) all sync an
http://en.wikipedia.org/wiki/Internet_Message_Access_Protocol[IMAP]
server to a Maildir filesystem.

#### Options

* http://isync.sourceforge.net/[mbsync, aka isync]
* http://offlineimap.org[offlineimap]
* http://pyropus.ca/software/getmail[getmail]

#### Choice

I've currently chosen http://isync.sourceforge.net/[mbsync, aka isync].

#### Comments

* I've used mbsync more than any other tool listed here, and it's
  thus far working nicely.
* Search http://bit.ly/1EdmDkW["mbsync vs offlineimap"] to see more.
* I understand getmail the least. It's less referenced (on
  the web) for this usage/context than either offlineimap
  or mbsync. Why is this? Is it not a viable alternative to
  the above? http://pyropus.ca/software/getmail[getmail's
  website] seems to primarily (?) pitch it as a
  http://sourceforge.net/projects/fetchmail/[fetchmail] replacement.

### Notmuch installation and initial configuration

* Best I can tell, I've completed this.

### Notmuch initial + automated tagging

(I've not yet started this implementation.)

* https://readthedocs.org/projects/afew[afew] best?
* http://www.procmail.org/[procmail]?
* See <<initial_tagging>> and <<auto_tagging>> for more.

### Auto-detect if IMAP resync needed

(I've not yet started this implementation.)

#### client->server checking

* mbsync-watcher
** https://github.com/tim-smart/node-mbsync-watcher
** https://www.npmjs.com/package/mbsync-watcher
** my take: it's good for client->server updates, and not vice versa
** Problem: I do _not_ want it to sync _all_ my 4k+ folders every 5
   minutes, as that's too much overhead. Hopefully there's a way to disable
   this.

#### server->client checking

* https://github.com/athoune/imapidle + some of my own Python scripting, which
  I'm hopeful will not be difficult.
*  mswatch
**   http://mswatch.sourceforge.net
**   requires IMAP-server-side shell access - difficult if not impossible
     to get for all my IMAP accounts.
**   this might also be a client->server option
**   wrapping `imapidle` with a `mbsync` trigger seems like a better,
     more-flexible alternative

[id='MUA_choice']
### MUA

(My implementation is currently in progress.)

#### Summary

Along with <<initial_tagging>>, <<MUA_choice,MUA introduction
and mastery>> appears to represent the largest learning curve.
http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz] and
https://github.com/pazz/alot[alot] currently present the most-attractive
solutions (for me), but it's early.

#### Details

* http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz]
** seems to be the most-popular MUA in this space
** http://notmuchmail.org/mutttips
** https://raw.githubusercontent.com/karelzak/mutt-kz/master/README.notmuch

* https://github.com/pazz/alot[alot]

** https://github.com/pazz/alot[alot] looks tremendously promising,
   possibly my best long-term solution, especially given
   <<my_user_profile,my user profile>> (namely I'm a vim user and a
   Python programmer--seems to mirror well). However, the available
   documentation/resources are far more sparse than say mutt-kz. The
   user-manual content is almost impeccable, and pazz seems to do a
   great job to stay on top of all issues and offer a professional
   solution. For example, I significantly appareciate the up-front,
   informationally-dense, bulleted feature list at the top of the
   https://github.com/pazz/alot/blob/master/README.md[alot README].
   However, it's thus far been hard to find practical resources like
   example config files, procedural setup, etc. Maybe this is due in
   part because it's not yet as popular, or caters to a user base more
   willing to spend time learning/configuring/tinkering with one tool,
   or something else?

*** Speculating: a hopefully-small effort to provide setup + config-file
    examples might go a long way to solve this problem, and boost alot's
    "new user uptake" populartiy.

* vim front-end for Notmuch
** http://git.notmuchmail.org/git/notmuch/blob/HEAD:/vim/README
** http://notmuchmail.org/vimtips/

** <<my_user_profile,I'm a heavy vim user>>, and while this approached
   seemed initially appealing, the depth of functionaly seems so
   (relatively) small that I haven't yet attempted to run this
   application. Am I overlooking a useful (in comparison to the others)
   tool?

* There's other http://notmuchmail.org/frontends[frontends]...

** ...but none seem as appealing to <<my_user_profile,me>> as the
   above. Am I overlooking any solutions that might fit well with my
   <<my_user_profile,user profile>>?

### Message tagging

(I've not yet started this implementation.)

* http://afew.readthedocs.org/en/latest[afew] currently looks best.

### Synchronizing Notmuch metadata across machines

(I've not yet started this implementation.)

* http://www.muchsync.org[muchsync] currently looks best.

** muchsync apparently syncs metadata _and_ data (it seems less
   efficient to be forced to copy the data, but this may be
   unavoidable), but claims to do it as efficiently as possible.

[id='user_adoption_challenges']
## Usage-Scenario Challenges in Priority-First Order

<<my_user_profile,My>> usage-scenario challenges include but may not be
limited to:

[id='which_MUAs']
### Which MUA(s)?

Decide which MUA(s) to use, particularly deciding on a primary MUA. This
is technically not a usage-scenario, but currently represents my biggest
challenge. See the <<MUA_choice,MUA options>>.

### Support old-style IMAP-folder paradigm

* While I may be be moving to a a tag-based paradigm, I still need
  to access my 4k+ IMAP folders as I did before, at least while I'm
  transitioning (presumably) from a folder-based to a tag-based
  paradigm. Any primary MUA/interface/IMAP-client I choose needs to
  support IMAP-folder-based paradigms (copying and moving to folders,
  etc) that I currently employ with <<the_problem,Mozilla Thunderbird>>.

[id='imap_account_separation']
### Support IMAP-account separation

. I have multiple email accounts, which is not uncommon. I want to
  "view" each one differently, such that emails and folders from account
  X does not clutter my view of emails/folders when viewing account Y.
. It would be extremely helpful to support a "combined" view of all my
  accounts, as an additional option. I stop just short of calling this an
  absolute requirement, simply because #1 is currently more important than
  #2.

[id='initial_tagging']
### Initial tagging
* http://notmuchmail.org/initial_tagging
* "tagging" my large set of IMAP folders
* in particular: `Inbox` and `Spam` folders -> tags
* Is https://readthedocs.org/projects/afew[afew] best for this?

### Moving msgs after applying tags

* Context, details:
  http://bit.ly/1GimL8Q[mutt-kz thread: "Moving msgs after applying tags?"].

* Will messages retain Notmuch-associated metadata (tags, etc) for
  lifetime of any message, including post-folder moves - without any
  special configuration?

** I'm used to moving messages between folders in order to classify.
   Further, I will like to keep a clean Inbox and other folders, for my
   non-Notmuch-based email clients, thus requiring message moving.

** Once I associate Notmuch-metadata (by adding tags, or whatever
   metadata/etc scenarios might be involved with Notmuch) with a
   message, I want (need?) said metadata/tags/etc to associate with a
   message forever, regardless of wherever I put said message. Is this
   the way it works "out of the box" with Notmuch-based systems?

### Piping email-message content through shell commands

Example potential solutions, not yet tested:

* http://www.davep.org/mutt/muttrc/macros.html
* http://wcm1.web.rice.edu/mutt-tips.html
* http://rhonda.deb.at/config/mutt/keys

I want to http://en.wikipedia.org/wiki/Pipeline_%28Unix%29["pipe"] the
content of:

. one email message,
. many email messages (by selecting multiple emails at the same time), or
. an entire IMAP folder of emails 

to any command/script of my choosing.

### Configure keyboard shortcuts to any command

Example potential solutions, not yet tested:

* http://rhonda.deb.at/config/mutt/keys
* http://dev.mutt.org/trac/wiki/MuttGuide/Macros
* http://www.mutt.org/doc/manual/manual-2.html

[id='IMAP_folders_as_tags',reftext='IMAP folders as tags']
### IMAP folders as tags
* http://notmuchmail.org/pipermail/notmuch/2010/003249.html
** http://notmuchmail.org/pipermail/notmuch/2010/003250.html

Also, see <<initial_tagging>>.

### Notmuch/MUA/mutt-kz/alot folder-based searching
* not yet certain how different this is from <<IMAP_folders_as_tags>>.
* http://notmuchmail.org/pipermail/notmuch/2011/thread.html#3707
* http://bit.ly/notmuch-folder-based-searching-nabble-2011

### Address-book/contacts integration

* http://notmuchmail.org/vimtips/#index1h2[Notmuch: Addressbook management
  and vim]
* http://stevelosh.com/blog/2012/10/the-homely-mutt/#contacts[mutt + contacts]

### Sync Notmuch tags with maildir flags
* https://github.com/spaetz/notmuchsync

### Managing message attachments
* <<forwarding_msgs_w_attachments>>
* opening attachments from MUA

[id='auto_tagging']
### Automatically tagging new messages (post initial tagging)

* http://afew.readthedocs.org/en/latest[afew]?

* http://notmuchmail.org/pipermail/notmuch/2012/thread.html#11055[employ
  procmail to set tags]?

* Can someone compare/contrast
  http://afew.readthedocs.org/en/latest[afew] and
  http://www.procmail.org/[procmail]?

### Syncing Notmuch metadata across machines
* http://www.muchsync.org
** In lieu of testing, this seems like the clear winner.
* http://notmuchmail.org/pipermail/notmuch/2010/003249.html
** http://notmuchmail.org/pipermail/notmuch/2010/003250.html
* http://www.reddit.com/r/linux/comments/2kcznk/notmuch_syncing_tags
** https://github.com/altercation/es-bin/blob/master/maildir-notmuch-sync
** https://lists.fedoraproject.org/pipermail/mutt-kz/2013-March/000136.html

### Offline editing - postponing drafts

* http://stevelosh.com/blog/2012/10/the-homely-mutt/#postponing-drafts[
  The Homely Mutt: Postponing Drafts]

### Writing HTML-formatted messages

* Haven't yet seen this solved.
* http://bit.ly/1dfWYmr[This discussion] might be useful.

[id='forwarding_msgs_w_attachments']
### Forwarding messages with attachments

* alot appears to https://github.com/pazz/alot/issues/761[have issues
  with this]

* I'm wondering if mutt-kz or others do as well

[id='purpose_more_details']
## Appendix 1: Purpose: More Details

[id='my_user_profile']

### My "user profile"

* In summary, https://github.com/johnnyutahh[I'm] a vim and
  Python lover, a keyboard jockey, and a reasonably-experienced,
  fairly-technical, <<computer_please_be_faster_than_me,demanding>>
  user. And like many others, I receive a remarkable amount of email in
  diverse contexts.

* I'm historically-trained as a software and computer-systems engineer.

** I've significant experience with programming in a variety of
   programming languages and system-administering a variety of
   OSes including but not limited to: C, C\++, Java, Ada, perl,
   Python; Windows, many commercial Unix-es, Linux, VMS, MacOSX. My
   favorite "Swiss army knife" language is Python. If I've time,
   I'm open to extending/fixing Python programs. I'd like to learn
   https://www.ruby-lang.org[Ruby] and https://golang.org[Go].

* I'm now more of a "business person." In spite of this:

** vim remains my primary editor (I hate moving my hand from the
   keyboard to the mouse or trackpad),
** Mac OS X is my primary computing machine,
** and I still significantly code in Python to solve "glueware" problems.
** I also still dabble in Linux (mostly Debian/Ubuntu) and MacOSX sysadmin.
* Learning new systems/languages/applications/software is old hat...
** ...but it's now harder only because of time constraints from expanded
   business responsibilities.

[id='computer_please_be_faster_than_me']

* Some might describe me as an impatient, unforgiving computing
  user. I _hate_ being faster than the computer. Further, when the
  computer/software/application says it's job is done, I want it to
  be _done_. However, some environments and applications perform
  significant, asynchronous activity even after reporting they are done
  servicing a request. (<<the_problem,Thunderbird>> is notorious for
  this.) And this drives me nuts. "Computer, if you need more time to
  complete a job, don't lie to me. I can go do other things while I wait
  for you. But please do not delay me further after you already said you
  were done."

Despite my history assimilating to new applications/environments, the
tag-based-classification paradigm still seems _significantly_ different
and a bit daunting to this "old school IMAP-folder user", and may (or
may not?) take some time to master. See <<user_adoption_challenges>>.
For example, opening https://github.com/pazz/alot[alot] for the first
time and looking at a staggering 50k+ emails in my "inbox" can give
someone pause; hopefully <<initial_tagging>> will take care of that.

[id='existing_tag_based_user_intro_docs_appear_to_be_lacking']

Further, the tag-based documentation resources--to describe
new-user-paradigm-shifts and present the most-popular toolsets--seem
scattered, disjointed, and/or non-existent for many scenarios / from
many perspectives. Hence this document. Obviously, I'd love to find any
similar, previously-overlooked documentation resource.

[id='why_spend_the_effort_to_write_this_doc']
### Why write this doc?

Why did I spend the time to write this document, instead of just trying
all the tools?

. *Email is too important not to "get it right."* Or at least, email
is too "frequent," probably my most-frequent life activity (very
unfortunately).

. *Brute-force "experience" may be too inefficient*. I'd rather learn
from others' experiences rather than inefficiently reply them all
myself.

. *This document may help future newbies.* And possibly accelerate
new-user population growth.

. *Defining requirements up front: this usually works.* Rarely have I
regretted taking the time to well-define requirements (separate from
design and/or solution) for any significant software or tool-adoption
project.

. *I might learn something I wouldn't have previously found*. It's
possible this document might attract enough attention for people to
offer solutions (applications, workflows, or whatever) I might not have
otherwise discovered. Ever.

. *Breaking my production email "IMAP database" would be very... bad.*
My businesses and projects rely on my email system to be top-notch
solid. If my email gets corrupted, lost, etc - things go very bad, very
fast. Especially if I'm _unknowingly_ messing up my email. Hence, I'm
rather cautious about correct implementation.

In any case, I'm hopeful that experienced and diverse feedback
from the tag-based-email-using communities can help avoid these
problems. At least, it seemed like the most-effective way, as the space
<<existing_tag_based_user_intro_docs_appear_to_be_lacking,doesn't (yet)
seem friendly to newbies>>.

[id='problem_details']
## Appendix 2: More Problem Details

(DISCLAIMER: This section's under construction, and not complete.)

OS X is great, but TB is difficult.
https://www.mozilla.org/en-US/thunderbird[Thunderbird] is old, buggy,
troublesome, slow, basically inextensible (for me, anyway), and as
I understand it, feature frozen. I'm tired of debating with the
mozillaZine support team about TB's bugs and limitations. Among other
things, it's IMAP sync is slow and unreliable. It literally (and
unfortunately, inconsistently) deletes IMAP folders on it's own whim,
asynchronously, sometimes when I least expect it. Sometimes it loses
track of the folders it didn't delete, and simply creates new ones,
bloating my mbox (TB only reliably supports mbox) files terribly over
time.

Additionally, the TB text/formatting editor is legendarily bad/buggy.
I'd desperately prefer to simply edit in vim, and edit rich/html text in
markdown or asciidoc and convert to html with a rendering engine, and I
suspect I could script-integrate such capability... if I had an MUA that
could play nicely with external scripts.

Further, I'm a keyboard jockey--eg: vim lover--and Python
programmer. I've maxed out TB's keyboard-shortcut-ness (eg:
https://addons.mozilla.org/en-us/thunderbird/addon/nostalgy[TB's
Nostalgy add-on]) best I can tell, and it's still limiting. I have
external tools (some developed by me and/or my team) to parse and
perform "magic" (like task-tracking and bug-report integration) on
email folders and individual messages, and TB--with it's lack of
proper maildir support and difficult extensibility--makes it extremely
difficult if not impossible to integrate with the external tools.

In short, it's time to move on from
https://www.mozilla.org/en-US/thunderbird[Thunderbird].

## Appendix 3: General Setup Guides

(Previously-referenced guides or sections of guides listed elsewhere in
this doc are not duplicated here. The following is provided here for my
general reference; maybe others will find these references useful.)

* http://dbp.io/essays/2013-06-21-hackers-replacement-for-gmail.html
* Mutt + Notmuch
  (non- http://kzak.redcrew.org/doku.php?id=mutt:start[mutt-kz] style)
** http://stevelosh.com/blog/2012/10/the-homely-mutt/
*** may get replaced by mutt-kz, but other things possibly still useful:
**** http://stevelosh.com/blog/2012/10/the-homely-mutt/#full-text-searching
* mutt in general
** http://wcm1.web.rice.edu/mutt-tips.html
** http://www.guckes.net/Mutt/setup.html
** http://objectmix.com/mutt/202060-whaaah-cant-see-svens-setup-page.html
* http://bit.ly/notmuch--how-i-learned-to-stop-worrying-and-love-the-mail

{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}
{blank}

